// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tgacdsphesepjzmiaxsz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRnYWNkc3BoZXNlcGp6bWlheHN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NzY5MzksImV4cCI6MjA1OTQ1MjkzOX0.vZnzyKIdJ0UKwXDWMUv0Y8dPagdcnQDhnTtikAjzwBA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);